# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4494658a762b35fcda532839b733826b615aa6f2267398edbfe5f1acdb7011b8851ececbef35f4a43cf97cf61ff53b697b5ea707a071d69afdebc7f54854f2a1

test:
  secret_key_base: c300c0f666f7446e31015ffd2ca67dbe8f00a6317712a27da4b0f6e125ef27c6872bbcf496789d4f51d9ae10e0e75bd9affd7df18215dc8331417f3feec02d59

# Do not keep production or staging secrets in the repository,
# instead set them in the .env file in root directory.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
