set :domain, 'prisoners.jumpstart.ge'
set :user, 'prisoners'
set :application, 'Prisoners'
set :repository, 'https://github.com/JumpStartGeorgia/Azerbaijan-Political-Prisoners.git'
set :repo_branch, 'master'
set :web_url, 'prisoners.watch'
set :use_ssl, true
set :puma_thread_count, '2,4'
set :puma_worker_count, '2'
