set :domain, 'prisoners.watch'
set :user, 'prisoners'
set :application, 'Prisoners'
set :repository, 'git@github.com:JumpStartGeorgia/Azerbaijan-Political-Prisoners.git'
set :web_url, 'prisoners.watch'
