set :domain, 'alpha.jumpstart.ge'
set :user, 'prisoners-prod'
set :application, 'Azeri-Prisoners'
set :repository, 'git@github.com:JumpStartGeorgia/Azerbaijan-Political-Prisoners.git'
set :web_url, 'prisoners.jumpstart.ge'
