set :domain, 'alpha.jumpstart.ge'
set :user, 'prisoners-staging'
set :application, 'Azeri-Prisoners-Staging'
set :repository, 'git@github.com:JumpStartGeorgia/Azerbaijan-Political-Prisoners.git'
set :repo_branch, 'master'
set :web_url, 'dev-prisoners.jumpstart.ge'
set :use_ssl, true
set :visible_to_robots, false
set :puma_thread_count, '1,1'
set :puma_worker_count, '1'
