set :domain, 'alpha.jumpstart.ge'
set :user, 'prisoners-staging'
set :application, 'Azeri-Prisoners-Staging'
set :repository, 'git@github.com:JumpStartGeorgia/Azerbaijan-Political-Prisoners.git'
set :web_url, 'dev-prisoners.jumpstart.ge'
