require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PrisonsController, :type => :controller do

  let(:user_manager_role) { FactoryGirl.create(:role, name: 'user_manager') }
  let(:user) { FactoryGirl.create(:user, role: user_manager_role) }

  before(:example) {
    sign_in :user, user
  }

  # This should return the minimal set of attributes required to create a valid
  # Prison. As you add validations to Prison, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.attributes_for(:prison, name: 'MyName') }

  let(:invalid_attributes) { FactoryGirl.attributes_for(:prison, name: '') }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrisonsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all prisons as @prisons" do
      prison = Prison.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:prisons)).to eq([prison])
    end
  end

  describe "GET show" do
    it "assigns the requested prison as @prison" do
      prison = Prison.create! valid_attributes
      get :show, {:id => prison.to_param}, valid_session
      expect(assigns(:prison)).to eq(prison)
    end
  end

  describe "GET new" do
    it "assigns a new prison as @prison" do
      get :new, {}, valid_session
      expect(assigns(:prison)).to be_a_new(Prison)
    end
  end

  describe "GET edit" do
    it "assigns the requested prison as @prison" do
      prison = Prison.create! valid_attributes
      get :edit, {:id => prison.to_param}, valid_session
      expect(assigns(:prison)).to eq(prison)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Prison" do
        expect {
          post :create, {:prison => valid_attributes}, valid_session
        }.to change(Prison, :count).by(1)
      end

      it "assigns a newly created prison as @prison" do
        post :create, {:prison => valid_attributes}, valid_session
        expect(assigns(:prison)).to be_a(Prison)
        expect(assigns(:prison)).to be_persisted
      end

      it "redirects to the created prison" do
        post :create, {:prison => valid_attributes}, valid_session
        expect(response).to redirect_to(Prison.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prison as @prison" do
        post :create, {:prison => invalid_attributes}, valid_session
        expect(assigns(:prison)).to be_a_new(Prison)
      end

      it "re-renders the 'new' template" do
        post :create, {:prison => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        FactoryGirl.attributes_for(:prison, {name: 'NewName'})
      }

      it "updates the requested prison" do
        prison = Prison.create! valid_attributes
        put :update, {:id => prison.to_param, :prison => new_attributes}, valid_session
        prison.reload
      end

      it "assigns the requested prison as @prison" do
        prison = Prison.create! valid_attributes
        put :update, {:id => prison.to_param, :prison => valid_attributes}, valid_session
        expect(assigns(:prison)).to eq(prison)
      end

      it "redirects to the prison" do
        prison = Prison.create! valid_attributes
        put :update, {:id => prison.to_param, :prison => valid_attributes}, valid_session
        expect(response).to redirect_to(prison)
      end
    end

    describe "with invalid params" do
      it "assigns the prison as @prison" do
        prison = Prison.create! valid_attributes
        put :update, {:id => prison.to_param, :prison => invalid_attributes}, valid_session
        expect(assigns(:prison)).to eq(prison)
      end

      it "re-renders the 'edit' template" do
        prison = Prison.create! valid_attributes
        put :update, {:id => prison.to_param, :prison => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prison" do
      prison = Prison.create! valid_attributes
      expect {
        delete :destroy, {:id => prison.to_param}, valid_session
      }.to change(Prison, :count).by(-1)
    end

    it "redirects to the prisons list" do
      prison = Prison.create! valid_attributes
      delete :destroy, {:id => prison.to_param}, valid_session
      expect(response).to redirect_to(prisons_url)
    end
  end

end
